// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/inf451_g.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttendanceAPI_MarkAttendance_FullMethodName = "/inf451.AttendanceAPI/MarkAttendance"
)

// AttendanceAPIClient is the client API for AttendanceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttendanceAPIClient interface {
	MarkAttendance(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*MarkResponse, error)
}

type attendanceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceAPIClient(cc grpc.ClientConnInterface) AttendanceAPIClient {
	return &attendanceAPIClient{cc}
}

func (c *attendanceAPIClient) MarkAttendance(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*MarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkResponse)
	err := c.cc.Invoke(ctx, AttendanceAPI_MarkAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceAPIServer is the server API for AttendanceAPI service.
// All implementations must embed UnimplementedAttendanceAPIServer
// for forward compatibility.
type AttendanceAPIServer interface {
	MarkAttendance(context.Context, *MarkRequest) (*MarkResponse, error)
	mustEmbedUnimplementedAttendanceAPIServer()
}

// UnimplementedAttendanceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttendanceAPIServer struct{}

func (UnimplementedAttendanceAPIServer) MarkAttendance(context.Context, *MarkRequest) (*MarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAttendance not implemented")
}
func (UnimplementedAttendanceAPIServer) mustEmbedUnimplementedAttendanceAPIServer() {}
func (UnimplementedAttendanceAPIServer) testEmbeddedByValue()                       {}

// UnsafeAttendanceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendanceAPIServer will
// result in compilation errors.
type UnsafeAttendanceAPIServer interface {
	mustEmbedUnimplementedAttendanceAPIServer()
}

func RegisterAttendanceAPIServer(s grpc.ServiceRegistrar, srv AttendanceAPIServer) {
	// If the following call pancis, it indicates UnimplementedAttendanceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttendanceAPI_ServiceDesc, srv)
}

func _AttendanceAPI_MarkAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceAPIServer).MarkAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceAPI_MarkAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceAPIServer).MarkAttendance(ctx, req.(*MarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttendanceAPI_ServiceDesc is the grpc.ServiceDesc for AttendanceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendanceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inf451.AttendanceAPI",
	HandlerType: (*AttendanceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarkAttendance",
			Handler:    _AttendanceAPI_MarkAttendance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inf451_g.proto",
}
