// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: proto/inf451_g.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRequest) Reset() {
	*x = MarkRequest{}
	mi := &file_proto_inf451_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRequest) ProtoMessage() {}

func (x *MarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inf451_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRequest.ProtoReflect.Descriptor instead.
func (*MarkRequest) Descriptor() ([]byte, []int) {
	return file_proto_inf451_g_proto_rawDescGZIP(), []int{0}
}

func (x *MarkRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *MarkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MarkRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkResponse) Reset() {
	*x = MarkResponse{}
	mi := &file_proto_inf451_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkResponse) ProtoMessage() {}

func (x *MarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inf451_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkResponse.ProtoReflect.Descriptor instead.
func (*MarkResponse) Descriptor() ([]byte, []int) {
	return file_proto_inf451_g_proto_rawDescGZIP(), []int{1}
}

func (x *MarkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MarkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_inf451_g_proto protoreflect.FileDescriptor

const file_proto_inf451_g_proto_rawDesc = "" +
	"\n" +
	"\x14proto/inf451_g.proto\x12\x06inf451\"a\n" +
	"\vMarkRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"8\n" +
	"\fMarkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2L\n" +
	"\rAttendanceAPI\x12;\n" +
	"\x0eMarkAttendance\x12\x13.inf451.MarkRequest\x1a\x14.inf451.MarkResponseB\x0eZ\finf451/protob\x06proto3"

var (
	file_proto_inf451_g_proto_rawDescOnce sync.Once
	file_proto_inf451_g_proto_rawDescData []byte
)

func file_proto_inf451_g_proto_rawDescGZIP() []byte {
	file_proto_inf451_g_proto_rawDescOnce.Do(func() {
		file_proto_inf451_g_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inf451_g_proto_rawDesc), len(file_proto_inf451_g_proto_rawDesc)))
	})
	return file_proto_inf451_g_proto_rawDescData
}

var file_proto_inf451_g_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inf451_g_proto_goTypes = []any{
	(*MarkRequest)(nil),  // 0: inf451.MarkRequest
	(*MarkResponse)(nil), // 1: inf451.MarkResponse
}
var file_proto_inf451_g_proto_depIdxs = []int32{
	0, // 0: inf451.AttendanceAPI.MarkAttendance:input_type -> inf451.MarkRequest
	1, // 1: inf451.AttendanceAPI.MarkAttendance:output_type -> inf451.MarkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inf451_g_proto_init() }
func file_proto_inf451_g_proto_init() {
	if File_proto_inf451_g_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inf451_g_proto_rawDesc), len(file_proto_inf451_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inf451_g_proto_goTypes,
		DependencyIndexes: file_proto_inf451_g_proto_depIdxs,
		MessageInfos:      file_proto_inf451_g_proto_msgTypes,
	}.Build()
	File_proto_inf451_g_proto = out.File
	file_proto_inf451_g_proto_goTypes = nil
	file_proto_inf451_g_proto_depIdxs = nil
}
